codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 5
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

ignore:
  - "**/test_*.rb"
  - "db/**/*"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, sunburst, diff, flags, files, footer"
  behavior: default
  require_changes: no